cc_test(
  name = "algorithms-test",
  srcs = ["unit_tests.cc", "sudoku_test.cpp"],
  copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//include:algorithms",
    ],
)
